Option no 2
TomBenDor/AP1 pull request #42
Opened 2021-09-19 10:23 UTC by OmerShoulstein

2021-09-19 10:35 UTC, TomBenDor requested changes

2021-09-19 10:35 UTC, TomBenDor commented on ex3/server/changeAlgoSettings.h
> +            newDistance = &euclideanDistance;
Turn inputDistance into lowercase and then compare:
https://stackoverflow.com/questions/313970/how-to-convert-an-instance-of-stdstring-to-lower-case

2021-09-19 10:35 UTC, TomBenDor commented on ex3/CMakeLists.txt
> +        server/DefaultIO.h server/Command.cpp server/StandardIO.cpp server/StandardIO.h server/changeAlgoSettings.h
Should ne ChangeAlgoSettings

2021-09-19 10:35 UTC, TomBenDor commented on ex3/server/Command.h
> +    virtual DefaultIO *getDefaultIO();
Why it's not abstract?
```suggestion
    virtual std::string getDescription() = 0;

    virtual DefaultIO *getDefaultIO() = 0;
```

2021-09-19 10:36 UTC, OmerShoulstein commented on ex3/server/Command.h
> +    virtual DefaultIO *getDefaultIO();
because it is implemented

2021-09-21 20:39 UTC, TomBenDor approved these changes

2021-09-21 20:39 UTC, merged